
name: vdock_env

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.8
  - rdkit=2023.09.2
  - pandas=2.0.3
  - pytorch=2.1.1
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - pytorch-cuda=12.1

